# 1c publication
Alias "/aiagents" "C:/basepublish/"
<Directory "C:/basepublish/">
    AllowOverride All
    Options None
    Order allow,deny
    Allow from all
    SetHandler 1c-application
    ManagedApplicationDescriptor "C:/basepublish/default.vrd"
</Directory>

# 1c publication
Alias "/mcptest" "C:/basepublish/mcp/"
<Directory "C:/basepublish/mcp/">
    AllowOverride All
    Options None
    Order allow,deny
    Allow from all
    SetHandler 1c-application
    ManagedApplicationDescriptor "C:/basepublish/mcp/default.vrd"
</Directory>
